apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flaskapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: flaskapp
          image: bibekk477/gha-argocd-k8s-pipeline:98d5b
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: image-pull-secret
