name: CICD pipeline for Flask app
on:
  push:
    branches: [ main ]

jobs:
  flask-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

- name: Build & Push Docker Image
  uses: docker/build-push-action@v4
  with:
    context: .
    push: true
    username: ${{ vars.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    tags: bibekk477/gha-argocd-k8s-pipeline:${GITHUB_SHA::5}
        